//
//  VisionDocumentRecognizer.swift
//  MultiScan
//
//  The Vision side of OCR, on the Swift-native Vision API (iOS/macOS 26+): `RecognizeDocumentsRequest` instead of the Objective-C era `VNRecognizeTextRequest`.
//
//  ## Why RecognizeDocumentsRequest
//  `RecognizeTextRequest` returns a flat list of lines. `RecognizeDocumentsRequest` understands the *page*: it groups lines into paragraphs (so two narrow columns with a thin gutter don't get read straight across), detects tables and lists, flags a title, and still exposes every line with its geometry. That structure is what Smart Separate (gutter detection), inline tables, chapter detection, and the per-page layout store all need — so Vision runs on **every** import, even when the user picked a transformer model as the primary OCR engine (see `OCRService`).
//
//  ## Orientation
//  Vision analyzes the pixels it is given. A phone photo stored with an EXIF orientation is *rotated pixels + a tag*, so the recognizer must be told the tag (`ImageRequestHandler(_:orientation:)`), otherwise it is reading sideways text. The old implementation didn't pass it. Regions come back normalized to the *oriented* image, which is also what the viewer shows, so `VisionDocumentLayout` records the oriented pixel size.
//
//  ## Coordinates
//  Vision's normalized rectangles have a lower-left origin. `VisionDocumentLayout` stores everything with an **upper-left** origin (0…1), the convention of every drawing API the app uses (SwiftUI, Core Graphics contexts in the capture overlay, `PageCapture.normalizedRect`). The flip happens once, here.
//
//  ⚠️ Compiled in the cloud without the SDK. API names follow the Vision documentation for 26/27 (`RecognizeDocumentsRequest`, `DocumentObservation.Container`, `RecognizedTextObservation`, `NormalizedRegion`); anything marked `REVIEW:` is a property whose exact spelling could not be verified against the headers.
//

import Foundation
import CoreGraphics
import ImageIO
import Vision

// MARK: - Stored layout

/// A normalized rectangle (0…1) with an upper-left origin. Codable scalars rather than `CGRect` so the plist encoding is stable across platforms.
nonisolated struct NormalizedBox: Codable, Sendable, Equatable, Hashable {
    var x: Double
    var y: Double
    var width: Double
    var height: Double

    var minX: Double { x }
    var maxX: Double { x + width }
    var minY: Double { y }
    var maxY: Double { y + height }
    var midX: Double { x + width / 2 }
    var midY: Double { y + height / 2 }

    var cgRect: CGRect { CGRect(x: x, y: y, width: width, height: height) }

    init(x: Double, y: Double, width: Double, height: Double) {
        self.x = x
        self.y = y
        self.width = width
        self.height = height
    }

    init(_ rect: CGRect) {
        self.init(x: rect.origin.x, y: rect.origin.y, width: rect.width, height: rect.height)
    }

    /// Converts a Vision `NormalizedRect` (lower-left origin) to upper-left origin.
    init(flippingVision rect: CGRect) {
        self.init(x: rect.origin.x, y: 1 - (rect.origin.y + rect.height), width: rect.width, height: rect.height)
    }

    /// Scales to pixel coordinates (upper-left origin, as Core Graphics image contexts expect after flipping).
    func pixelRect(in size: CGSize) -> CGRect {
        CGRect(x: x * size.width, y: y * size.height, width: width * size.width, height: height * size.height)
    }

    /// Smallest box containing both.
    func union(_ other: NormalizedBox) -> NormalizedBox {
        let minX = min(self.minX, other.minX)
        let minY = min(self.minY, other.minY)
        let maxX = max(self.maxX, other.maxX)
        let maxY = max(self.maxY, other.maxY)
        return NormalizedBox(x: minX, y: minY, width: maxX - minX, height: maxY - minY)
    }

    static func union(of boxes: [NormalizedBox]) -> NormalizedBox? {
        guard var result = boxes.first else { return nil }
        for box in boxes.dropFirst() { result = result.union(box) }
        return result
    }
}

/// Everything MultiScan keeps from a `RecognizeDocumentsRequest` pass over one page image. Persisted on `Page.visionLayoutData` as a binary plist.
nonisolated struct VisionDocumentLayout: Codable, Sendable, Equatable {
    /// Bump when the structure changes; `decode` returns nil for other versions so callers fall back gracefully (the layout is derived data and can be regenerated by re-running Vision on the page image).
    static let currentVersion = 1

    /// One recognized line: Vision's top transcript candidate and its box.
    struct Line: Codable, Sendable, Equatable {
        var text: String
        var box: NormalizedBox
    }

    /// A paragraph: Vision's grouping of lines that read together (one column, one block). `box` is the union of the lines.
    struct Paragraph: Codable, Sendable, Equatable {
        var text: String
        var box: NormalizedBox
        var lines: [Line]
    }

    /// A table cell; ranges are row/column indices (a merged cell spans several).
    struct TableCell: Codable, Sendable, Equatable {
        var rowStart: Int
        var rowEnd: Int        // inclusive
        var columnStart: Int
        var columnEnd: Int     // inclusive
        var text: String
        var box: NormalizedBox
    }

    struct Table: Codable, Sendable, Equatable {
        var box: NormalizedBox
        /// Rows of cells, in reading order. Row/column counts come from the ranges.
        var rows: [[TableCell]]

        var rowCount: Int { (rows.flatMap { $0 }.map(\.rowEnd).max() ?? -1) + 1 }
        var columnCount: Int { (rows.flatMap { $0 }.map(\.columnEnd).max() ?? -1) + 1 }
    }

    struct ListBlock: Codable, Sendable, Equatable {
        var box: NormalizedBox
        var items: [String]
    }

    var version: Int = currentVersion

    /// Pixel size of the *oriented* image the regions are normalized against.
    var imageWidth: Int
    var imageHeight: Int

    /// Full-page transcript in reading order (Vision's `Container.Text.transcript`).
    var transcript: String

    /// Vision's title detection (`Container.title`), if any — a strong hint for `ChapterDetector` and `ProjectTitleSuggester`.
    var title: String?

    var paragraphs: [Paragraph]
    var tables: [Table]
    var lists: [ListBlock]

    /// BCP-47 identifiers of the recognized languages, when Vision reports them.
    var languages: [String]

    /// Every line across all paragraphs, in document order — what Smart Separate and the capture overlay snap to.
    var allLines: [Line] { paragraphs.flatMap(\.lines) }

    var imageSize: CGSize { CGSize(width: imageWidth, height: imageHeight) }

    // MARK: Persistence

    func encoded() -> Data? {
        let encoder = PropertyListEncoder()
        encoder.outputFormat = .binary
        return try? encoder.encode(self)
    }

    static func decode(_ data: Data?) -> VisionDocumentLayout? {
        guard let data,
              let layout = try? PropertyListDecoder().decode(VisionDocumentLayout.self, from: data),
              layout.version == currentVersion else { return nil }
        return layout
    }

    /// The legacy `boundingBoxesData` shape (lower-left-origin `CGRect`s per line), so older code paths that still read `Page.boundingBoxes` keep working for new pages if ever needed.
    func legacyBoundingBoxesData() -> Data? {
        let rects = allLines.map { line -> CGRect in
            CGRect(x: line.box.x, y: 1 - line.box.maxY, width: line.box.width, height: line.box.height)
        }
        return try? JSONEncoder().encode(rects)
    }
}

// MARK: - Recognizer

/// Stateless, `nonisolated`: called from `OCRService`'s `@concurrent` per-image work.
nonisolated enum VisionDocumentRecognizer {

    /// Runs document recognition on an already-decoded image.
    /// - Parameters:
    ///   - cgImage: the raw decoded bitmap (NOT pre-rotated).
    ///   - orientation: the EXIF orientation of `cgImage`, so Vision reads the text upright. Regions are returned relative to the upright image.
    static func recognize(_ cgImage: CGImage, orientation: CGImagePropertyOrientation) async throws -> VisionDocumentLayout {
        var request = RecognizeDocumentsRequest()
        request.textRecognitionOptions.useLanguageCorrection = true
        request.textRecognitionOptions.automaticallyDetectLanguage = true

        let handler = ImageRequestHandler(cgImage, orientation: orientation)
        let observations = try await handler.perform(request)

        let orientedSize = orientedPixelSize(of: cgImage, orientation: orientation)
        guard let document = observations.first?.document else {
            // Vision found no document structure at all (blank page, photo of a wall). Return an empty layout so the page still gets created.
            return VisionDocumentLayout(
                imageWidth: Int(orientedSize.width), imageHeight: Int(orientedSize.height),
                transcript: "", title: nil, paragraphs: [], tables: [], lists: [], languages: []
            )
        }

        return layout(from: document, orientedSize: orientedSize)
    }

    /// Builds the stored layout from a Vision container. Separate so a cell's nested container can reuse the paragraph/line mapping.
    private static func layout(from document: DocumentObservation.Container, orientedSize: CGSize) -> VisionDocumentLayout {
        let paragraphs: [VisionDocumentLayout.Paragraph] = document.paragraphs.map { paragraph in
            let lines: [VisionDocumentLayout.Line] = paragraph.lines.map { line in
                VisionDocumentLayout.Line(
                    text: line.transcript,
                    box: NormalizedBox(flippingVision: line.boundingRegion.boundingBox.cgRect)
                )
            }
            return VisionDocumentLayout.Paragraph(
                text: paragraph.transcript,
                box: NormalizedBox(flippingVision: paragraph.boundingRegion.boundingBox.cgRect),
                lines: lines
            )
        }

        let tables: [VisionDocumentLayout.Table] = document.tables.map { table in
            let rows: [[VisionDocumentLayout.TableCell]] = table.rows.map { row in
                row.map { cell in
                    VisionDocumentLayout.TableCell(
                        rowStart: cell.rowRange.lowerBound,
                        rowEnd: cell.rowRange.upperBound,
                        columnStart: cell.columnRange.lowerBound,
                        columnEnd: cell.columnRange.upperBound,
                        text: cell.content.text.transcript,
                        box: NormalizedBox(flippingVision: cell.content.boundingRegion.boundingBox.cgRect)
                    )
                }
            }
            return VisionDocumentLayout.Table(
                box: NormalizedBox(flippingVision: table.boundingRegion.boundingBox.cgRect),
                rows: rows
            )
        }

        let lists: [VisionDocumentLayout.ListBlock] = document.lists.map { list in
            VisionDocumentLayout.ListBlock(
                box: NormalizedBox(flippingVision: list.boundingRegion.boundingBox.cgRect),
                items: list.items.map(\.itemString)
            )
        }

        // Languages are reported per line; collect the distinct set in first-seen order.
        var languages: [String] = []
        for paragraph in document.paragraphs {
            for line in paragraph.lines {
                for language in line.recognitionLanguages {
                    let identifier = language.minimalIdentifier
                    if !languages.contains(identifier) { languages.append(identifier) }
                }
            }
        }

        return VisionDocumentLayout(
            imageWidth: Int(orientedSize.width),
            imageHeight: Int(orientedSize.height),
            transcript: document.text.transcript,
            title: document.title?.transcript,
            paragraphs: paragraphs,
            tables: tables,
            lists: lists,
            languages: languages
        )
    }

    /// Pixel size after applying `orientation` (90°/270° orientations swap width and height).
    static func orientedPixelSize(of cgImage: CGImage, orientation: CGImagePropertyOrientation) -> CGSize {
        switch orientation {
        case .left, .leftMirrored, .right, .rightMirrored:
            return CGSize(width: cgImage.height, height: cgImage.width)
        default:
            return CGSize(width: cgImage.width, height: cgImage.height)
        }
    }

    /// EXIF orientation of the first image in `source` (`.up` when absent).
    static func exifOrientation(of source: CGImageSource) -> CGImagePropertyOrientation {
        guard let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let raw = properties[kCGImagePropertyOrientation] as? UInt32,
              let orientation = CGImagePropertyOrientation(rawValue: raw) else {
            return .up
        }
        return orientation
    }
}
